-- ============================================================================
-- v297 — Venue As-Of Integrity Corrective
-- GENERATED by tools/build_v297_migration.py — do not hand-edit; rebuild.
-- source: db/captured/functions.sql sha256[:16]=0761ce0acecb2bdc
--         db/captured/schema.sql    sha256[:16]=a2dd5c4e13e9929b
--         repo HEAD 63a14b4 · 10 sanctioned insertions, 7 bodies + 1 marker
-- ============================================================================

begin;

do $preflight$
begin
  if exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace
             where n.nspname='public' and p.proname='venue_asof_integrity') then
    raise exception 'V297_ALREADY_APPLIED';
  end if;
  if (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace
       where n.nspname='public' and p.proname='occurrence_current_venue') <> 1 then
    raise exception 'V297_PREFLIGHT_FAILED: occurrence_current_venue absent or overloaded — CREATE OR REPLACE would mis-target';
  end if;
  if to_regprocedure('public.occurrence_current_venue(uuid, timestamp with time zone)') is null then
    raise exception 'V297_PREFLIGHT_FAILED: occurrence_current_venue exists but NOT with the captured identity (uuid, timestamp with time zone) — CREATE OR REPLACE would create a new overload, not replace';
  end if;
  if (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace
       where n.nspname='public' and p.proname='current_observation') <> 1 then
    raise exception 'V297_PREFLIGHT_FAILED: current_observation absent or overloaded — CREATE OR REPLACE would mis-target';
  end if;
  if to_regprocedure('public.current_observation(uuid, uuid, text, timestamp with time zone, text[])') is null then
    raise exception 'V297_PREFLIGHT_FAILED: current_observation exists but NOT with the captured identity (uuid, uuid, text, timestamp with time zone, text[]) — CREATE OR REPLACE would create a new overload, not replace';
  end if;
  if (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace
       where n.nspname='public' and p.proname='venue_profile_read') <> 1 then
    raise exception 'V297_PREFLIGHT_FAILED: venue_profile_read absent or overloaded — CREATE OR REPLACE would mis-target';
  end if;
  if to_regprocedure('public.venue_profile_read(uuid, uuid, text, timestamp with time zone, text[])') is null then
    raise exception 'V297_PREFLIGHT_FAILED: venue_profile_read exists but NOT with the captured identity (uuid, uuid, text, timestamp with time zone, text[]) — CREATE OR REPLACE would create a new overload, not replace';
  end if;
  if (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace
       where n.nspname='public' and p.proname='venue_knowledge_findings') <> 1 then
    raise exception 'V297_PREFLIGHT_FAILED: venue_knowledge_findings absent or overloaded — CREATE OR REPLACE would mis-target';
  end if;
  if to_regprocedure('public.venue_knowledge_findings(uuid, timestamp with time zone, text[])') is null then
    raise exception 'V297_PREFLIGHT_FAILED: venue_knowledge_findings exists but NOT with the captured identity (uuid, timestamp with time zone, text[]) — CREATE OR REPLACE would create a new overload, not replace';
  end if;
  if (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace
       where n.nspname='public' and p.proname='venue_profile') <> 1 then
    raise exception 'V297_PREFLIGHT_FAILED: venue_profile absent or overloaded — CREATE OR REPLACE would mis-target';
  end if;
  if to_regprocedure('public.venue_profile(uuid, timestamp with time zone, text[])') is null then
    raise exception 'V297_PREFLIGHT_FAILED: venue_profile exists but NOT with the captured identity (uuid, timestamp with time zone, text[]) — CREATE OR REPLACE would create a new overload, not replace';
  end if;
  if (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace
       where n.nspname='public' and p.proname='venue_contradictions') <> 1 then
    raise exception 'V297_PREFLIGHT_FAILED: venue_contradictions absent or overloaded — CREATE OR REPLACE would mis-target';
  end if;
  if to_regprocedure('public.venue_contradictions(uuid, timestamp with time zone, text[])') is null then
    raise exception 'V297_PREFLIGHT_FAILED: venue_contradictions exists but NOT with the captured identity (uuid, timestamp with time zone, text[]) — CREATE OR REPLACE would create a new overload, not replace';
  end if;
  if (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace
       where n.nspname='public' and p.proname='venue_verification_requirement') <> 1 then
    raise exception 'V297_PREFLIGHT_FAILED: venue_verification_requirement absent or overloaded — CREATE OR REPLACE would mis-target';
  end if;
  if to_regprocedure('public.venue_verification_requirement(uuid, timestamp with time zone, text[])') is null then
    raise exception 'V297_PREFLIGHT_FAILED: venue_verification_requirement exists but NOT with the captured identity (uuid, timestamp with time zone, text[]) — CREATE OR REPLACE would create a new overload, not replace';
  end if;
end $preflight$;

-- ── occurrence_current_venue · as-of bounded ──
CREATE OR REPLACE FUNCTION public.occurrence_current_venue(p_occurrence uuid, p_now timestamp with time zone DEFAULT now())
 RETURNS TABLE(source text, venue_id uuid, venue_name text, venue_address text, binding_id uuid)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  with occ as (
    select 'occurrence'::text as source, v.venue_id, v.venue_name_snapshot,
           v.venue_address_snapshot, v.id, v.seq
      from public.occurrence_venue_binding v
     where v.occurrence_id = p_occurrence
       and v.tenant_id = public.current_tenant_id()
       and v.recorded_at <= p_now
       and not exists (select 1 from public.occurrence_venue_binding s
                        where s.replaces_id = v.id and s.recorded_at <= p_now)
     order by v.seq desc limit 1),
  eng as (
    select 'engagement'::text as source, b.venue_id, b.venue_name_snapshot,
           b.venue_address_snapshot, b.id, b.seq
      from public.engagement_venue_binding b
      join public.engagement_occurrence o on o.booking_id = b.booking_id
     where o.id = p_occurrence and b.created_at <= p_now
       and b.tenant_id = public.current_tenant_id()
       and not exists (select 1 from public.engagement_venue_binding s
                        where s.replaces_binding_id = b.id and s.created_at <= p_now)
     order by b.seq desc limit 1)
  select source, venue_id, venue_name_snapshot, venue_address_snapshot, id
    from (select * from occ union all select * from eng) u
   order by case when u.source = 'occurrence' then 0 else 1 end
   limit 1;
$function$;

-- ── current_observation · as-of bounded ──
CREATE OR REPLACE FUNCTION public.current_observation(p_venue uuid, p_scope_space uuid, p_attribute text, p_context timestamp with time zone DEFAULT now(), p_conditions text[] DEFAULT NULL::text[])
 RETURNS uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select o.id
  from public.venue_observation o
  where o.tenant_id = public.current_tenant_id()
    and o.venue_id in (select public.venue_family(public.resolve_venue(p_venue)))
    and o.attribute_key = p_attribute
    and (o.scope_space_id is not distinct from p_scope_space)
    and not exists (select 1 from public.venue_observation_supersession s where s.observation_id = o.id)
    and (o.effective_at is null or o.effective_at <= p_context) and o.observed_at <= p_context
    and (o.expires_at   is null or o.expires_at   >  p_context)
    and (o.condition_key is null or (p_conditions is not null and o.condition_key = any(p_conditions)))
  order by public.source_class_rank(o.source_class) asc, o.observed_at desc, o.created_at desc
  limit 1;
$function$;

-- ── venue_profile_read · as-of bounded ──
CREATE OR REPLACE FUNCTION public.venue_profile_read(p_venue uuid, p_scope_space uuid, p_attribute text, p_context timestamp with time zone DEFAULT now(), p_conditions text[] DEFAULT NULL::text[])
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_gov uuid; g record; d record; v_contra jsonb := null;
begin
  if public.resolve_venue(p_venue) is null then return null; end if;   -- cross-tenant: nothing
  v_gov := public.current_observation(p_venue, p_scope_space, p_attribute, p_context, p_conditions);
  if v_gov is null then
    return jsonb_build_object('status','unobserved','attribute',p_attribute,'scope_space',p_scope_space);
  end if;
  select * into g from public.venue_observation where id = v_gov;
  -- contradiction: a NEWER, LOWER-class, applicable, unsuperseded observation
  -- whose value materially differs. It never overrides; it derives a finding.
  select o.* into d from public.venue_observation o
    where o.tenant_id = public.current_tenant_id()
      and o.venue_id in (select public.venue_family(public.resolve_venue(p_venue)))
      and o.attribute_key = p_attribute
      and (o.scope_space_id is not distinct from p_scope_space)
      and not exists (select 1 from public.venue_observation_supersession s where s.observation_id = o.id)
      and (o.effective_at is null or o.effective_at <= p_context) and o.observed_at <= p_context
      and (o.expires_at   is null or o.expires_at   >  p_context)
      and (o.condition_key is null or (p_conditions is not null and o.condition_key = any(p_conditions)))
      and public.source_class_rank(o.source_class) > public.source_class_rank(g.source_class)
      and o.observed_at > g.observed_at
      and o.value is distinct from g.value
    order by o.observed_at desc limit 1;
  if found then
    v_contra := jsonb_build_object('disputing_observation', d.id, 'source_class', d.source_class,
                                   'observed_at', d.observed_at, 'value', d.value, 'observer', d.observer);
  end if;
  return jsonb_build_object(
    'status', case when g.value_kind = 'absent' then 'observed_absent' else 'observed' end,
    'attribute', p_attribute, 'scope_space', p_scope_space,
    'value', g.value, 'value_kind', g.value_kind, 'narrative', g.narrative,
    'source_class', g.source_class, 'observed_at', g.observed_at, 'observer', g.observer,
    'observation_id', g.id, 'evidence_refs', to_jsonb(g.evidence_refs),
    'contradiction', v_contra);
end $function$;

-- ── venue_knowledge_findings · as-of bounded ──
CREATE OR REPLACE FUNCTION public.venue_knowledge_findings(p_venue uuid, p_at timestamp with time zone DEFAULT now(), p_conditions text[] DEFAULT NULL::text[])
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_canon uuid; k record; prof jsonb; pol record; fnd jsonb := '[]'::jsonb;
  v_reno_eff timestamptz; exp record; v_fam text; v_age_days numeric;
begin
  v_canon := public.resolve_venue(p_venue);
  if v_canon is null then return null; end if;

  for k in
    select distinct o.scope_space_id, o.attribute_key
    from public.venue_observation o
    where o.observed_at <= p_at and o.tenant_id = public.current_tenant_id()
      and o.venue_id in (select public.venue_family(v_canon))
      and o.attribute_key <> 'renovation_event'
  loop
    v_fam := public.attribute_family(k.attribute_key);
    select * into pol from public.effective_staleness_policy(v_fam);
    prof := public.venue_profile_read(v_canon, k.scope_space_id, k.attribute_key, p_at, p_conditions);

    if prof->>'status' = 'unobserved' then
      -- expired vs never-known: an unsuperseded observation exists but its
      -- explicit expiry precedes the evaluation date → EXPIRED (critical)
      select o.id, o.expires_at into exp from public.venue_observation o
        where o.observed_at <= p_at and o.tenant_id = public.current_tenant_id()
          and o.venue_id in (select public.venue_family(v_canon))
          and o.attribute_key = k.attribute_key
          and (o.scope_space_id is not distinct from k.scope_space_id)
          and o.expires_at is not null and o.expires_at <= p_at
          and not exists (select 1 from public.venue_observation_supersession s where s.observation_id = o.id)
        order by o.expires_at desc limit 1;
      if found then
        fnd := fnd || jsonb_build_object('kind','expired','severity','critical',
          'family',v_fam,'attribute',k.attribute_key,'scope_space',k.scope_space_id,
          'observation_id',exp.id,'expired_at',exp.expires_at,
          'reason', k.attribute_key||' expired '||to_char(exp.expires_at,'YYYY-MM-DD')||' — before the evaluation date');
      end if;
      continue;
    end if;

    -- renovation invalidation (critical, regardless of freshness otherwise)
    select max(coalesce(o.effective_at, o.observed_at)) into v_reno_eff
      from public.venue_observation o
      where o.tenant_id = public.current_tenant_id()
        and o.venue_id in (select public.venue_family(v_canon))
        and o.attribute_key = 'renovation_event'
        and not exists (select 1 from public.venue_observation_supersession s where s.observation_id = o.id)
        and coalesce(o.effective_at, o.observed_at) <= p_at
        and (o.scope_space_id is null or public.space_within(k.scope_space_id, o.scope_space_id))
        and coalesce(o.effective_at, o.observed_at) > (prof->>'observed_at')::timestamptz;
    if v_reno_eff is not null then
      fnd := fnd || jsonb_build_object('kind','renovation_reverification','severity','critical',
        'family',v_fam,'attribute',k.attribute_key,'scope_space',k.scope_space_id,
        'observation_id',prof->>'observation_id','renovated_at',v_reno_eff,
        'reason', k.attribute_key||' predates the '||to_char(v_reno_eff,'YYYY-MM-DD')||' renovation — re-verify');
    end if;

    -- contradiction carry-through (single source: the profile)
    if prof->'contradiction' is not null and prof->'contradiction' <> 'null'::jsonb then
      fnd := fnd || jsonb_build_object('kind','contradiction_unresolved','severity','critical',
        'family',v_fam,'attribute',k.attribute_key,'scope_space',k.scope_space_id,
        'observation_id',prof->>'observation_id','disputed_by',prof->'contradiction'->>'disputing_observation',
        'reason', k.attribute_key||' has a newer conflicting '||replace(prof->'contradiction'->>'source_class','_',' ')||' — resolve or supersede');
    end if;

    -- age staleness — ONLY for observations without explicit expiry (ruling 4)
    if (select expires_at from public.venue_observation where id = (prof->>'observation_id')::uuid) is null
       and pol.max_age_days is not null then
      v_age_days := extract(epoch from (p_at - (prof->>'observed_at')::timestamptz)) / 86400.0;
      if v_age_days > pol.max_age_days then
        fnd := fnd || jsonb_build_object('kind','stale','severity',pol.severity,
          'family',v_fam,'attribute',k.attribute_key,'scope_space',k.scope_space_id,
          'observation_id',prof->>'observation_id','age_days',round(v_age_days),
          'reason', k.attribute_key||' last verified '||to_char((prof->>'observed_at')::timestamptz,'YYYY-MM-DD')||' — over the '||pol.max_age_days||'-day '||v_fam||' threshold');
      end if;
    end if;
  end loop;

  -- unobserved verify_required families (ruling 11)
  for pol in
    select p.attribute_family as fam from public.venue_staleness_policy p
     where p.tenant_id = public.current_tenant_id() and p.verify_required
  loop
    if not exists (
      select 1 from public.venue_observation o
       where o.observed_at <= p_at and o.tenant_id = public.current_tenant_id()
         and o.venue_id in (select public.venue_family(v_canon))
         and o.attribute_key <> 'renovation_event'
         and public.attribute_family(o.attribute_key) = pol.fam
         and not exists (select 1 from public.venue_observation_supersession s where s.observation_id = o.id))
    then
      fnd := fnd || jsonb_build_object('kind','unobserved','severity','critical',
        'family',pol.fam,'attribute',null,'scope_space',null,
        'reason', pol.fam||' knowledge is required by policy but has never been observed at this venue');
    end if;
  end loop;

  return coalesce((select jsonb_agg(e order by e->>'kind', e->>'family', coalesce(e->>'attribute',''), coalesce(e->>'scope_space',''))
                   from jsonb_array_elements(fnd) e), '[]'::jsonb);
end $function$;

-- ── venue_profile · as-of bounded ──
CREATE OR REPLACE FUNCTION public.venue_profile(p_venue uuid, p_context timestamp with time zone DEFAULT now(), p_conditions text[] DEFAULT NULL::text[])
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce(jsonb_agg(
           public.venue_profile_read(p_venue, k.scope_space_id, k.attribute_key, p_context, p_conditions)
           order by k.attribute_key), '[]'::jsonb)
  from (select distinct o.scope_space_id, o.attribute_key
          from public.venue_observation o
         where o.observed_at <= p_context and o.tenant_id = public.current_tenant_id()
           and o.venue_id in (select public.venue_family(public.resolve_venue(p_venue)))) k;
$function$;

-- ── venue_contradictions · as-of bounded ──
CREATE OR REPLACE FUNCTION public.venue_contradictions(p_venue uuid, p_context timestamp with time zone DEFAULT now(), p_conditions text[] DEFAULT NULL::text[])
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce(jsonb_agg(e), '[]'::jsonb) from (
    select public.venue_profile_read(p_venue, k.scope_space_id, k.attribute_key, p_context, p_conditions) e
      from (select distinct o.scope_space_id, o.attribute_key
              from public.venue_observation o
             where o.observed_at <= p_context and o.tenant_id = public.current_tenant_id()
               and o.venue_id in (select public.venue_family(public.resolve_venue(p_venue)))) k
  ) q where e->'contradiction' is not null and e->>'contradiction' is not null;
$function$;

-- ── venue_verification_requirement · as-of bounded ──
CREATE OR REPLACE FUNCTION public.venue_verification_requirement(p_venue uuid, p_at timestamp with time zone DEFAULT now(), p_conditions text[] DEFAULT NULL::text[])
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_canon uuid; fnd jsonb; crit jsonb; n_fam int; has_wide_reno boolean; walked int; verdict text; reasons jsonb;
begin
  v_canon := public.resolve_venue(p_venue);
  if v_canon is null then return null; end if;
  fnd := public.venue_knowledge_findings(p_venue, p_at, p_conditions);
  select coalesce(jsonb_agg(e), '[]'::jsonb) into crit
    from jsonb_array_elements(fnd) e where e->>'severity' = 'critical';
  select count(distinct e->>'family') into n_fam from jsonb_array_elements(crit) e;
  select exists (select 1 from jsonb_array_elements(crit) e
                  where e->>'kind'='renovation_reverification' and e->>'scope_space' is null) into has_wide_reno;
  -- venue-wide renovation: any wide reno event that invalidated anything
  if not has_wide_reno then
    select exists (
      select 1 from jsonb_array_elements(crit) e
       where e->>'kind'='renovation_reverification'
         and exists (select 1 from public.venue_observation o
                      where o.attribute_key='renovation_event' and o.scope_space_id is null
                        and o.venue_id in (select public.venue_family(v_canon))
                        and coalesce(o.effective_at,o.observed_at) <= p_at)) into has_wide_reno;
  end if;
  select count(*) into walked from public.venue_walkthrough
    where conducted_at <= p_at and tenant_id = public.current_tenant_id() and venue_id in (select public.venue_family(v_canon));
  select coalesce(jsonb_agg(e->>'reason'), '[]'::jsonb) into reasons from jsonb_array_elements(crit) e;

  if jsonb_array_length(crit) = 0 then verdict := 'none';
  elsif n_fam >= 3 or has_wide_reno or walked = 0 then verdict := 'walkthrough_required';
  else verdict := 'targeted_verification';
  end if;
  return jsonb_build_object('verification', verdict, 'critical_count', jsonb_array_length(crit),
                            'critical_families', n_fam, 'reasons', reasons, 'findings', fnd);
end $function$;

-- deployment marker: replace-only releases need one for --verify resumability
create function public.venue_asof_integrity() returns text
language sql immutable as $$ select 'v297' $$;

commit;
