-- ============================================================================
-- v310.1 · TENANT INTEGRITY — FORWARD TERMINAL NORMALIZATION
-- File: supabase/v310_1_tenant_integrity.sql            min_release v310
--
-- A tenant-scoped column must derive its tenant from the acting session, never
-- from a constant compiled in at migration time.
--
-- ── THE DEFECT, AND WHY IT IS NOT VISIBLE TO A LITERAL SEARCH ───────────────
-- Three frozen historical migrations share one pattern — v182_blueprints.sql,
-- v227_brand.sql and v233_photography.sql:
--
--   select id into bb from tenants where slug = 'burger-bar';
--   if bb is not null then
--     execute 'alter table X add column if not exists tenant_id uuid references tenants(id)';
--     execute format('update X set tenant_id = %L where tenant_id is null', bb);
--     execute format('alter table X alter column tenant_id set default %L', bb);
--   end if;
--
-- The default is GENERATED by format(), so the tenant UUID never appears in the
-- repository as a literal. It appears only in a database that replayed the
-- chain while a tenant slugged burger-bar existed. Two databases replaying the
-- same chain therefore reach different schemas, which is the whole defect.
--
-- ── HISTORICAL MIGRATIONS ARE IMMUTABLE ─────────────────────────────────────
-- Architect ruling: none of the three is edited. v310.1 is the FORWARD TERMINAL
-- NORMALIZATION for this capability. The governing invariant is convergence,
-- not retroactive innocence:
--
--   a database that reaches v310.1 through ANY supported predecessor state
--   converges to the same lawful terminal tenant-integrity state.
--
-- A historical migration may still create the old shape during replay; this
-- release deterministically normalizes it before the terminal level is reached.
--
-- ── PREDECESSOR SHAPES, BOTH OBSERVED AND BOTH ACCEPTED ─────────────────────
-- A · the column exists carrying the literal-default defect. Observed in
--     EventCore production for proposal_versions, photo_library and
--     publication_themes.
-- B · the column is ABSENT, because the guarded historical block never fired
--     for want of a burger-bar tenant. Observed in the certification database
--     for blueprints, photo_library and publication_themes.
--
-- Every statement below is written to accept both and to be re-runnable.
--
-- ── FOUR SURFACES, ONE DEFECT FAMILY ────────────────────────────────────────
-- blueprints is included because the chain can still produce the old literal
-- default for it on replay, even though EventCore production already reads
-- current_tenant_id() there. That production state was corrected out of band
-- and never recorded in any release: PRE-EXISTING UNDOCUMENTED PRODUCTION DRIFT
-- — CAPABILITY NOW ABSORBED BY v310.1. Production is not reversed to match
-- history; the lawful terminal state is made explicit so the drift cannot recur
-- or diverge again.
--
-- ── CANONICAL COLUMN SEMANTICS, VERIFIED NOT GUESSED ────────────────────────
-- Read from EventCore production: uuid, nullable, foreign key to tenants(id)
-- with NO ACTION on delete and update — identical on all four surfaces.
-- Nullability is deliberately NOT normalized. proposal_versions.tenant_id is
-- NOT NULL in the certification database and nullable in production; changing
-- either would be a schema redesign, which this patch is not.
--
-- ── WHY A NULL IS THE RIGHT NEW FAILURE MODE ────────────────────────────────
-- After this change an insert with no tenant context resolves to NULL rather
-- than to a wrong tenant. That is a strict improvement: a NULL tenancy is
-- invisible to every tenant policy, so the row fails CLOSED and surfaces as a
-- missing row. The old behaviour failed OPEN — fully visible, to the wrong
-- tenancy. Where the column is NOT NULL the insert fails outright, which is
-- also closed.
--
-- ── BOUNDARY ────────────────────────────────────────────────────────────────
-- DATABASE-ONLY (Forward Process SOP Rule 1, Class A). No application file is
-- touched, so no application deploy occurs and the v309 deployment-ordering
-- finding is not exercised. No trigger, policy, helper function, provisioning
-- machinery or tenancy abstraction is created. No tenant is created, renamed or
-- removed. No data is purged. Booking CRM is a separate product on a separate
-- backend and is not contacted; the equivalent common-ancestor defect was
-- repaired there independently (Shared Cross-Product Ledger X-013).
-- ============================================================================

begin;

-- ── 1 · the four tenant-scoped surfaces exist with canonical semantics ──────
-- `if not exists` makes predecessor shape B converge without disturbing shape A.
-- The reference clause supplies the canonical foreign key when the column is
-- created here; where the column already exists the constraint already exists
-- with it. The proof asserts the foreign key on all four afterwards, so a
-- predecessor carrying the column WITHOUT its constraint fails loudly rather
-- than passing silently.
alter table public.proposal_versions  add column if not exists tenant_id uuid references public.tenants(id);
alter table public.photo_library      add column if not exists tenant_id uuid references public.tenants(id);
alter table public.publication_themes add column if not exists tenant_id uuid references public.tenants(id);
alter table public.blueprints         add column if not exists tenant_id uuid references public.tenants(id);

-- ── 2 · tenancy derives from the acting session, on all four ────────────────
alter table public.proposal_versions  alter column tenant_id set default public.current_tenant_id();
alter table public.photo_library      alter column tenant_id set default public.current_tenant_id();
alter table public.publication_themes alter column tenant_id set default public.current_tenant_id();
alter table public.blueprints         alter column tenant_id set default public.current_tenant_id();

-- ── 3 · proven mismatches only, derived from the authoritative parent ───────
-- The join IS the proof of correctness: a row is corrected only when its parent
-- proposal exists and declares a tenancy. `is distinct from` also repairs a NULL
-- child against a known parent, and never rewrites a row that already agrees.
--
-- photo_library, publication_themes and blueprints receive NO data repair. They
-- have no governing parent relation from which tenancy could be derived
-- unambiguously, so any speculative reassignment would be an invention. Rows
-- whose tenancy cannot be derived are left exactly as they are and reported by
-- the proof instead.
update public.proposal_versions pv
   set tenant_id = pr.tenant_id
  from public.proposals pr
 where pr.id = pv.proposal_id
   and pr.tenant_id is not null
   and pv.tenant_id is distinct from pr.tenant_id;

-- ── the deployed marker ─────────────────────────────────────────────────────
-- NO GRANT. The new function inherits the schema default, matching v306 through
-- v310. No existing grant is altered.
create function public.v310_1_tenant_integrity() returns text
language sql immutable as $$ select 'v310.1 · terminal normalization — tenant-scoped defaults derive from current_tenant_id() on all four surfaces; proposal_versions inherit parent proposal tenancy'::text $$;

commit;
